server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: service-user
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        - id: service-auth
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**

        - id: service-account
          uri: http://localhost:8083
          predicates:
            - Path=/api/accounts/**

        - id: service-card
          uri: http://localhost:8085
          predicates:
            - Path=/api/cards/**

        - id: service-payment
          uri: http://localhost:8086
          predicates:
            - Path=/api/payments/**

        - id: service-loan
          uri: http://localhost:8087
          predicates:
            - Path=/api/loans/**, /api/loan-payments/**, /api/loan-statuses/**

        - id: service-log
          uri: http://localhost:8088
          predicates:
            - Path=/api/logs/**

        - id: service-fraud
          uri: http://localhost:8089
          predicates:
            - Path=/api/fraud-alerts/**, /api/alert-types/**

        - id: service-employee
          uri: http://localhost:8090
          predicates:
            - Path=/api/employees/**, /api/employee-credentials/**

